# Generated by Django 5.2.7 on 2025-10-27 22:30

import apps.cargo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default=apps.cargo.models.generate_tracking_number, max_length=50, unique=True)),
                ('cargo_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('cargo_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cbm', models.DecimalField(decimal_places=2, help_text='Cubic meters', max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
                'db_table': 'cargo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo History',
                'verbose_name_plural': 'Cargo History',
                'db_table': 'cargo_history',
                'ordering': ['-updated_at'],
            },
        ),
    ]
